# Generated by Django 2.2.5 on 2024-04-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksheet',
            old_name='rollno',
            new_name='rollNo',
        ),
    ]
