# Generated by Django 2.2.5 on 2024-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_auto_20240426_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_remote_address', models.CharField(max_length=255)),
                ('http_remote_host', models.CharField(max_length=255)),
                ('http_remote_user', models.CharField(max_length=255)),
                ('http_host', models.CharField(max_length=255)),
                ('http_user_agent', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SOS_REQUEST_DATA',
            },
        ),
    ]
